# Generated by Django 5.1.4 on 2024-12-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_status_employee_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='stage',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('inactive', 'Inactive')], default='onboarding', max_length=20),
        ),
    ]
